version: 3.0.0
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/data/db
      - ./docker/postgres/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
